### ISSUE TITLE
Unified way to copy protobuff to Tensor

### ISSUE THREAD

**Issue by constroy** [InfiniTensor/InfiniTensor#107]
Currently we have to convert protobuf mssage to a `list` first, then to a `Tensor`.
`Tensor` has multiple `copyin` methods for different data types.

To unify and simplify these copy methods, there are two possible ways:

1. use third party protobuf binding
https://github.com/pybind/pybind11_protobuf

2. use official numpy binding (protobuff -> np.array -> Tensor)
https://pybind11.readthedocs.io/en/stable/advanced/pycpp/numpy.html

**Comment by PanZezhong1725** [comment]
Does not support converting gpu tensor to Numpy. Reopen issue.

**Comment by PanZezhong1725** [comment]
closed as fixed
