### ISSUE TITLE
Can InfiniTensor optimize any onnx model?

### ISSUE THREAD

**Issue by ntcmp2u** [InfiniTensor/InfiniTensor#146]
Hi, I am now trying to optimize my own model using InfiniTensor. The documents state that it can support Resnet18-v2, DenseNet-121-12, Inception-2, EfficientNet-Lite4. Since the model I would like to optimize is not in the list, I would like to know if it can support other onnx model.

**Comment by whjthu** [comment]
Hi, the latest verified support list of InfiniTensor can be found here: https://github.com/InfiniTensor/InfiniTensor/issues/145, and we are providing support for models in TorchVision and HuggingFace.

**Comment by whjthu** [comment]
Currently InfiniTensor is used as an Inference Engine. The ONNX output is mainly used for debugging.
