### ISSUE TITLE
Error: CUDA error (cudaGetLastError()): no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by deng-ShiFu** [InfiniTensor/InfiniTensor#161]
我在执行"make test-cpp"时出现了这个错误
![error](https://github.com/InfiniTensor/InfiniTensor/assets/73120065/04d85b94-5e83-44a7-8b53-99747f06d462)
在所有的60个测试用例中，几乎所有的与cuda相关的测试都出现了这个错误。
下面是我的GPU相关信息
![gpu](https://github.com/InfiniTensor/InfiniTensor/assets/73120065/6d5f9992-4f94-4051-b158-c12da7b2f25c)
我使用了项目中提供的docker环境，在单独的对cuda测试中，能够正常使用cuda。
请问你们遇到过这个问题吗，是如何解决的?

**Comment by deng-ShiFu** [comment]
这个问题是GPU算力设置错误导致的。
在项目CMakeLists文件中，将set_target_properties(InfiniTensor PROPERTIES CUDA_ARCHITECTURES "70;80")
中的"70;80"修改成本机对应的GPU算力即可

**Comment by whjthu** [comment]
谢谢，我们会在文档中添加相关说明
