### ISSUE TITLE
与TVM对比

### ISSUE THREAD

**Issue by deng-ShiFu** [InfiniTensor/InfiniTensor#166]
你好，我正在复现你们的论文，我想知道你们在评估时使用的TVM是否进行了调整，如果我使用python的TVM库是否能到达论文中的评估效果。谢谢

**Comment by deng-ShiFu** [comment]
谢谢你的回复。我还有两个问题
第一个问题：受制于我个人的水平，我无法在源码中确定"表达式推导"功能是在哪里实现的，能够麻烦你告诉我它是在哪个文件或者哪个类下面实现的吗
第二个问题：在你们的论文中提到了"EinNet-base"，请问在你们的项目中有没有实现"EinNet-base"，或者说是否有一个开关能够启用或者关闭优化，如果存在的话，能够麻烦你告诉我它在哪个位置吗。

谢谢

**Comment by zhengly123** [comment]
1. EinNet在工程中的名字为`nnet`，可以在`include/nnet`, `src/nnet`和`test/nnet`中找到相关代码
2. 由于正在迭代InfiniTensor后端部分，EinNet尚未完全更新至master。如现在用于测试，可先用[AE代码](https://github.com/zhengly123/OSDI23-EinNet-AE/blob/main/0_model/einnet/run_models.py)

**Comment by deng-ShiFu** [comment]
你好，我通过你们的[AE项目](https://github.com/zhengly123/OSDI23-EinNet-AE)，执行了resnet18和densenet，通过分析 `NMutator::runSingleOp`函数优化前后的变化，发现两个模型的变化均是由if和for捕获到特定算子并执行特定操作引起的。而对于那些执行了后面的表达式推导功能的算子，最终并没有产生有效的候选图。请问这一现象是正常的吗，如何解释这一现象？如果是正常的，那么表达式推导这一功能对于哪个模型具有优化贡献，或者说如何来证明表达式推导对于优化有贡献。

**Comment by zhengly123** [comment]
你好，现在全模型的优化中预置了一部分由公式推导发现的规则，相应的推导部分可以在[测试](https://github.com/zhengly123/OSDI23-EinNet-AE/tree/main/test/nnet)中查看，例如[test_OpSearch](https://github.com/zhengly123/OSDI23-EinNet-AE/blob/main/test/nnet/test_OpSearch.cc)中提供了几个卷积相关的变换。完整连接前端的计算图和后端公式推导后可实现等价效果。由于目前图接口还不稳定，会在前端重构完成后会再进行连接同时并入主线。
